<<<<<<< HEAD
version: '3'
=======
version: '3.10'
>>>>>>> b76081a8ec4b9a820a3d0f1adef71c7e7cef6824
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
<<<<<<< HEAD
      - .env
=======
      - .env
      - .env_start_app
#    depends_on:
#      - redis
#
#  redis:
#    image: redis:alpine
#    ports:
#      - "6379:6379"
>>>>>>> b76081a8ec4b9a820a3d0f1adef71c7e7cef6824
