version: '3.10'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
      - .env_start_app
#    depends_on:
#      - redis
#
#  redis:
#    image: redis:alpine
#    ports:
#      - "6379:6379"
