name: Deploy API

on:
  push:
    branches:
      - main
# test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     # Додайте команди для запуску ваших тестів

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no dmytro@31.220.75.30 "
          cd /home/dmytro/api && \
          git pull origin main && \
          sudo systemctl restart api.service"

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Deploy to server
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       username: ${{ secrets.SSH_USER }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       script: |
  #         cd /home/dmytro/api
  #         git pull origin main
  #         sudo systemctl restart api.service